# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  sqs_producer:
    restart: always
    build: .
    command: [ "python", "sqs_producer.py" ]
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
    volumes:
      - ./workers:/code
    depends_on:
      - localstack
  sqs_consumer:
    restart: always
    build: .
    command: [ "python", "sqs_consumer.py" ]
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - KAFKA_HOST=broker:9092
    volumes:
      - ./workers:/code
    depends_on:
      - localstack
      - broker

  image_extraction:
    restart: always
    build: .
    command: [ "faust", "-A", "image_extraction", "worker", "-l", "info", "--web-port", "6066" ]
    environment:
      - KAFKA_HOST=kafka://broker:9092
    volumes:
      - ./workers:/code
    depends_on:
      - broker
    ports:
      - "6066:6066"

  audit:
    restart: always
    build: .
    command: [ "faust", "-A", "audit", "worker", "-l", "info", "--web-port", "6067" ]
    environment:
      - KAFKA_HOST=kafka://broker:9092
    volumes:
      - ./workers:/code
    depends_on:
      - broker
    ports:
      - "6067:6067"

  echo:
    restart: always
    build: .
    command: [ "faust", "-A", "echo", "worker", "-l", "info", "--web-port", "6068" ]
    environment:
      - KAFKA_HOST=kafka://broker:9092
    volumes:
      - ./workers:/code
    depends_on:
      - broker
    ports:
      - "6068:6068"

  autotag:
    restart: always
    build: .
    command: [ "faust", "-A", "autotag", "worker", "-l", "info", "--web-port", "6069" ]
    environment:
      - KAFKA_HOST=kafka://broker:9092
    volumes:
      - ./workers:/code
    depends_on:
      - broker
    ports:
      - "6069:6069"

  scale_ai:
    restart: always
    build: .
    command: [ "faust", "-A", "scale_ai", "worker", "-l", "info", "--web-port", "6070" ]
    environment:
      - KAFKA_HOST=kafka://broker:9092
    volumes:
      - ./workers:/code
    depends_on:
      - broker
    ports:
      - "6070:6070"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: wurstmeister/kafka
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_CREATE_TOPICS: "image-extraction:1:1,prediction:1:1,audit:1:1,autotag:1:1,scale_ai:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  localstack:
    image: localstack/localstack:0.11.5
    ports:
      - "4566:4566"
      - "4570:4570"
      - "4572:4572"
    environment:
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - START_WEB=0
      - SERVICES=sqs:4570,s3:4572
      - DEBUG=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"